"""empty message

Revision ID: 1b4cff255837
Revises: 54422d2a0121
Create Date: 2024-05-09 18:10:46.279528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4cff255837'
down_revision = '54422d2a0121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couple', schema=None) as batch_op:
        batch_op.drop_constraint('fk_couple_match_id_competition', type_='foreignkey')
        batch_op.drop_column('match_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couple', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_couple_match_id_competition', 'competition', ['match_id'], ['id'])

    # ### end Alembic commands ###
