"""empty message

Revision ID: 54422d2a0121
Revises: d6d58409e2dd
Create Date: 2024-05-09 18:06:56.150931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54422d2a0121'
down_revision = 'd6d58409e2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couple', schema=None) as batch_op:
        batch_op.alter_column('user1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_couple_user2_id_user', type_='foreignkey')
        batch_op.drop_constraint('fk_couple_user1_id_user', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couple', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_couple_user1_id_user', 'user', ['user1_id'], ['id'])
        batch_op.create_foreign_key('fk_couple_user2_id_user', 'user', ['user2_id'], ['id'])
        batch_op.alter_column('user2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user1_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
