"""empty message

Revision ID: 583d5bab602a
Revises: 1b4cff255837
Create Date: 2024-05-09 21:53:14.753001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583d5bab602a'
down_revision = '1b4cff255837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_session_table')
    op.drop_table('session')
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('result')

    op.create_table('session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('result', sa.VARCHAR(length=10), nullable=False),
    sa.Column('match_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['competition.id'], name='fk_session_match_id_competition'),
    sa.PrimaryKeyConstraint('id', name='pk_session')
    )
    op.create_table('user_session_table',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name='fk_user_session_table_session_id_session'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_session_table_user_id_user'),
    sa.PrimaryKeyConstraint('user_id', 'session_id', name='pk_user_session_table')
    )
    # ### end Alembic commands ###
