"""empty message

Revision ID: 87df79296b04
Revises: d1ab54bff208
Create Date: 2024-04-26 11:51:08.660400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87df79296b04'
down_revision = 'd1ab54bff208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('released', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_column('released')

    # ### end Alembic commands ###
