"""empty message

Revision ID: d6d58409e2dd
Revises: f903f32d20c2
Create Date: 2024-05-09 18:04:13.586976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d58409e2dd'
down_revision = 'f903f32d20c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couple', schema=None) as batch_op:
        batch_op.alter_column('user1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_couple_user2_id_user'), 'user', ['user2_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_couple_user1_id_user'), 'user', ['user1_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couple', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_couple_user1_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_couple_user2_id_user'), type_='foreignkey')
        batch_op.alter_column('user2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user1_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
