"""empty message

Revision ID: f903f32d20c2
Revises: 87df79296b04
Create Date: 2024-05-09 17:13:45.912845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f903f32d20c2'
down_revision = '87df79296b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couple',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['competition.id'], name=op.f('fk_couple_match_id_competition')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_couple'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('couple')
    # ### end Alembic commands ###
